
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kaustubh
 */
public class Deletebusdetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form Deletebusdetails
     */
    public Deletebusdetails() {
        initComponents();
        Deletebusdetails();
    }
    public void infoMessage(String message,String title){
 JOptionPane.showMessageDialog(null, message, title,JOptionPane.INFORMATION_MESSAGE);
 
 }
public void Deletebusdetails(){
           try{
           Class.forName("com.mysql.jdbc.Driver");
            String databaseURL="jdbc:mysql://localhost:3306/busm";
            Connection con=DriverManager.getConnection(databaseURL,"root","");
            Statement stat =con.createStatement();
            String selectQuery="select * from  bus_details ";
            ResultSet rs=stat.executeQuery(selectQuery);  
    
            while(rs.next())
            {
            String bus_no=rs.getString("bus_no");
            String bus_source=rs.getString("bus_source");
            String bus_dest=rs.getString("bus_dest");
            String Movement=rs.getString("Movement");
           String Time=String.valueOf(rs.getTime("Time"));
           String Date=rs.getString("Date");
           String price=rs.getString("price");
           String seat=rs.getString("seat");
           
           String tbData[] = {bus_no,bus_source,bus_dest,Movement,Time,Date,seat,price,	seat};
           DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblModel.addRow(tbData);
            }
           }
           catch(Exception e){
        System.out.println(e);
        }
          
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Delete busdetails");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus No", "Source", "Destination", "Date", "Movement", "Time", "price", "Seat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
            String databaseURL="jdbc:mysql://localhost:3306/busm";
            Connection con=DriverManager.getConnection(databaseURL,"root","");
            Statement stat =con.createStatement();
            String selectQuery="select * from  bus_details ";
            ResultSet rs=stat.executeQuery(selectQuery);  
    
            while(rs.next())
            {
            String bus_no=rs.getString("bus_no");
            String bus_source=rs.getString("bus_source");
            String bus_dest=rs.getString("bus_dest");
            String Movement=rs.getString("Movement");
           String Time=String.valueOf(rs.getTime("Time"));
           String Date=rs.getString("Date");
           String price=rs.getString("price");
           String seat=rs.getString("seat");
           
           String tbData[] = {bus_no,bus_source,bus_dest,Movement,Time,Date,seat,price,	seat};
           DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
          
           
           JOptionPane.showConfirmDialog(null,"Do you to delete the  record ?");
            
                int SelectedRowIndex = jTable1.getSelectedRow();
            tblModel.removeRow(SelectedRowIndex);
            
            JOptionPane.showMessageDialog(this, "Record Deleted ");
            }
            
            
        }
        catch(Exception e){
        System.out.println(e);
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
